import { JobRoles} from "../../modal/Job-roles.model";

export var jobs : JobRoles[] = [
  {code: '001', cat: 'IT Related', job: 'IT Engineer'},
  {code: '002', cat: 'IT Related', job: 'IT Support Engineer'},
  {code: '003', cat: 'IT Related', job: 'Software Engineer'},
  {code: '004', cat: 'IT Related', job: 'Web Developer'},
  {code: '005', cat: 'IT Related', job: 'Backend Engineer'},
  {code: '006', cat: 'IT Related', job: 'Frontend Engineer'},
  {code: '007', cat: 'IT Related', job: 'Fullstack Developer'},
  {code: '008', cat: 'IT Related', job: 'Network Engineer'},
  {code: '009', cat: 'IT Related', job: 'Devops Engineer'},
  {code: '010', cat: 'IT Related', job: 'Help Support'},
  {code: '011', cat: 'IT Related', job: 'Project Manager'},
  {code: '012', cat: 'IT Related', job: 'Tester'},
  {code: '013', cat: 'Art & Design Related', job: 'Graphic Designer'},
  {code: '014', cat: 'Art & Design Related', job: 'Web Designer'},
  {code: '015', cat: 'Art & Design Related', job: 'Illustrator Designer'},
  {code: '016', cat: 'Art & Design Related', job: 'Photographer'},
  {code: '017', cat: 'Art & Design Related', job: 'Video Editor'},
  {code: '018', cat: 'Art & Design Related', job: 'Banner Designer'},
  {code: '019', cat: 'Art & Design Related', job: 'Flyer Designer'},
  {code: '020', cat: 'Art & Design Related', job: 'Poster Designer'},
  {code: '020', cat: 'Business Related', job: 'HR Manager'},
  {code: '021', cat: 'Business Related', job: 'Accountant'},
  {code: '022', cat: 'Business Related', job: 'Sales'},
  {code: '023', cat: 'Business Related', job: 'Marketing'},
  {code: '024', cat: 'Business Related', job: 'Finance'},
  {code: '025', cat: 'Business Related', job: 'Secretary'},
];
